### PR TITLE
Use render to get the rendered CSS.

### PR DESCRIPTION
**Pull request by rwjblue**
`Ember.View.prototype.renderToBuffer` was private API and is removed on current master.

This swaps to using all public API surface, and works properly on all three Ember channels (stable, beta, and canary).  It should work all the way back to 1.0 (though I didn't test that far).

### CODE REVIEW

**Comment by rwjblue** [comment]
@rpflorence - Any way this can be merged/tagged/released?

Currently, ic-modal does not function on canary (which will become 1.8.0-beta.1 in the next day or so).

---

For anyone that stumbles across this with an error you can use this for now via the following in `bower.json`:

```
    "ic-styled": "rwjblue/ic-styled#fix-for-metal-views"
```

**Comment by ryanflorence** [comment]
yes, I was out yesterday, should be able to do this today.

**Comment by rwjblue** [comment]
@rpflorence - Any updates here?

**Comment by ryanflorence** [comment]
Been heads down on other stuff, but I actually planned to address this (and the other components) today :)

**Comment by ryanflorence** [comment]
closed by 60b54b97341237d54a61e8109f7482eaed90f8e2

thanks for the prompt fix @rwjblue, sorry I couldn't get to it sooner. will have releases for all the components depending on this today too :)

**Comment by rwjblue** [comment]
As noted above, this was closed and merged manually in 60b54b9.

**Pull request closed without merging**
